"""initial schema: 16 tables

Revision ID: 63d88c66eb52
Revises: 
Create Date: 2026-08-27 07:51:00.017314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63d88c66eb52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_label', sa.Text(), nullable=False),
    sa.Column('root_cause_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_clusters'))
    )
    op.create_table('loans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Text(), nullable=False),
    sa.Column('borrower_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='ingested', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ingested', 'in_review', 'verified', 'rejected')", name=op.f('ck_loans_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans')),
    sa.UniqueConstraint('loan_id', name=op.f('uq_loans_loan_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('operator', 'reviewer', 'consumer')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.Column('prev_event_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('human', 'ai', 'system')", name=op.f('ck_audit_events_actor_type_valid')),
    sa.CheckConstraint("event_type IN ('file_uploaded', 'record_imported', 'validation_executed', 'exception_created', 'ai_recommendation_generated', 'reviewer_comment_added', 'field_edited', 'loan_approved', 'loan_rejected', 'verified_record_created', 'verified_record_exported', 'rule_created', 'rule_deactivated', 'correction_requested', 'trust_config_updated')", name=op.f('ck_audit_events_event_type_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_audit_events_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_events_seq'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_loan_seq', ['loan_id', 'seq'], unique=False)

    op.create_table('loan_canonical',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pinned_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_canonical_loan_id_loans')),
    sa.PrimaryKeyConstraint('loan_id', name=op.f('pk_loan_canonical'))
    )
    op.create_table('raw_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_kind', sa.Text(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('parsed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmapped_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("file_kind IN ('loan_tape', 'servicer_update', 'document_manifest')", name=op.f('ck_raw_files_file_kind_valid')),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name=op.f('ck_raw_files_status_valid')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_raw_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_files'))
    )
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.create_index('ix_raw_files_file_hash', ['file_hash'], unique=False)

    op.create_table('source_trust_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trust_score BETWEEN 0 AND 100', name=op.f('ck_source_trust_config_trust_score_range')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_source_trust_config_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_trust_config')),
    sa.UniqueConstraint('source_system', 'field_name', name='source_field_unique')
    )
    with op.batch_alter_table('source_trust_config', schema=None) as batch_op:
        batch_op.create_index('uq_trust_base_score', ['source_system'], unique=True, postgresql_where=sa.text('field_name IS NULL'))

    op.create_table('validation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('natural_language_source', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("scope IN ('row', 'dataset', 'cross_source')", name=op.f('ck_validation_rules_scope_valid')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_validation_rules_severity_valid')),
    sa.CheckConstraint("source IN ('seed', 'ai_generated', 'manual')", name=op.f('ck_validation_rules_source_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_validation_rules_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_rules')),
    sa.UniqueConstraint('rule_code', 'version', name='code_version_unique')
    )
    op.create_table('verified_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('canonical_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_recommendation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('trust_score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_hash', sa.Text(), nullable=False),
    sa.Column('prev_record_hash', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trust_score BETWEEN 0 AND 100', name=op.f('ck_verified_records_trust_score_range')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_verified_records_loan_id_loans')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_verified_records_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verified_records')),
    sa.UniqueConstraint('loan_id', 'version', name='loan_version_unique')
    )
    op.create_table('raw_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_file_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], name=op.f('fk_raw_records_raw_file_id_raw_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_records')),
    sa.UniqueConstraint('raw_file_id', 'row_number', name='row_unique_per_file')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('raw_record_id', sa.Uuid(), nullable=True),
    sa.Column('raw_file_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('ai_severity', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('is_blocking', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ai_severity IS NULL OR ai_severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_exceptions_ai_severity_valid')),
    sa.CheckConstraint("exception_type IN ('validation_failure', 'source_conflict', 'staleness', 'duplicate', 'import_error')", name=op.f('ck_exceptions_exception_type_valid')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_exceptions_severity_valid')),
    sa.CheckConstraint("status IN ('open', 'in_review', 'resolved', 'rejected')", name=op.f('ck_exceptions_status_valid')),
    sa.CheckConstraint('loan_id IS NOT NULL OR raw_record_id IS NOT NULL', name=op.f('ck_exceptions_exception_has_subject')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_exceptions_assigned_to_users')),
    sa.ForeignKeyConstraint(['cluster_id'], ['exception_clusters.id'], name=op.f('fk_exceptions_cluster_id_exception_clusters')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_exceptions_loan_id_loans')),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_files.id'], name=op.f('fk_exceptions_raw_file_id_raw_files')),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], name=op.f('fk_exceptions_raw_record_id_raw_records')),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], name=op.f('fk_exceptions_rule_id_validation_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.create_index('ix_exceptions_queue', ['status', 'severity', 'cluster_id'], unique=False)
        batch_op.create_index('ix_exceptions_raw_file_id', ['raw_file_id'], unique=False)

    op.create_table('loan_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('raw_record_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('origin', sa.Text(), server_default='import', nullable=False),
    sa.CheckConstraint("origin IN ('import', 'human_edit')", name=op.f('ck_loan_records_origin_valid')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_records_loan_id_loans')),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], name=op.f('fk_loan_records_raw_record_id_raw_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_records')),
    sa.UniqueConstraint('loan_id', 'source_system', 'version', name='revision_unique_per_source')
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('evidence_bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_field', sa.Text(), nullable=True),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('suggested_source', sa.Text(), nullable=True),
    sa.Column('suggested_severity', sa.Text(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_model_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('explain_failure', 'suggest_correction', 'reviewer_note', 'classify_severity', 'batch_summary')", name=op.f('ck_ai_recommendations_action_type_valid')),
    sa.CheckConstraint("suggested_severity IS NULL OR suggested_severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_ai_recommendations_suggested_severity_valid')),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name=op.f('ck_ai_recommendations_confidence_range')),
    sa.ForeignKeyConstraint(['cluster_id'], ['exception_clusters.id'], name=op.f('fk_ai_recommendations_cluster_id_exception_clusters')),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], name=op.f('fk_ai_recommendations_exception_id_exceptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_ai_recommendations_exception_id', ['exception_id'], unique=False)

    op.create_table('exception_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_drafted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_exception_comments_author_id_users')),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], name=op.f('fk_exception_comments_exception_id_exceptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_comments'))
    )
    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_record_id', sa.Uuid(), nullable=True),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("result IN ('pass', 'fail', 'not_applicable')", name=op.f('ck_validation_results_result_valid')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_validation_results_loan_id_loans')),
    sa.ForeignKeyConstraint(['loan_record_id'], ['loan_records.id'], name=op.f('fk_validation_results_loan_record_id_loan_records')),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], name=op.f('fk_validation_results_rule_id_validation_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index('ix_validation_results_loan_result', ['loan_id', 'result'], unique=False)

    op.create_table('reviewer_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('decision_scope', sa.Text(), server_default='exception', nullable=False),
    sa.Column('ai_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('request_correction', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('agreed_with_ai', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(decision_scope = 'exception' AND exception_id IS NOT NULL) OR (decision_scope = 'loan'      AND loan_id      IS NOT NULL)", name=op.f('ck_reviewer_decisions_decision_has_subject')),
    sa.CheckConstraint("action IN ('accept', 'edit', 'reject', 'manual_resolution', 'approve_loan', 'reject_loan')", name=op.f('ck_reviewer_decisions_action_valid')),
    sa.CheckConstraint("decision_scope IN ('exception', 'loan')", name=op.f('ck_reviewer_decisions_decision_scope_valid')),
    sa.ForeignKeyConstraint(['ai_recommendation_id'], ['ai_recommendations.id'], name=op.f('fk_reviewer_decisions_ai_recommendation_id_ai_recommendations')),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], name=op.f('fk_reviewer_decisions_exception_id_exceptions')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_reviewer_decisions_loan_id_loans')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviewer_decisions_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_decisions'))
    )
    with op.batch_alter_table('reviewer_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_reviewer_decisions_batch_id', ['batch_id'], unique=False)
        batch_op.create_index('ix_reviewer_decisions_exception_id', ['exception_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewer_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_reviewer_decisions_exception_id')
        batch_op.drop_index('ix_reviewer_decisions_batch_id')

    op.drop_table('reviewer_decisions')
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_validation_results_loan_result')

    op.drop_table('validation_results')
    op.drop_table('exception_comments')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_recommendations_exception_id')

    op.drop_table('ai_recommendations')
    op.drop_table('loan_records')
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.drop_index('ix_exceptions_raw_file_id')
        batch_op.drop_index('ix_exceptions_queue')

    op.drop_table('exceptions')
    op.drop_table('raw_records')
    op.drop_table('verified_records')
    op.drop_table('validation_rules')
    with op.batch_alter_table('source_trust_config', schema=None) as batch_op:
        batch_op.drop_index('uq_trust_base_score', postgresql_where=sa.text('field_name IS NULL'))

    op.drop_table('source_trust_config')
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_files_file_hash')

    op.drop_table('raw_files')
    op.drop_table('loan_canonical')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_loan_seq')

    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('loans')
    op.drop_table('exception_clusters')
    # ### end Alembic commands ###
